language: scala

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"
  - "$HOME/.cache/coursier"

scala:
- 2.11.8
- 2.12.3

jdk:
- openjdk8

script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage formatCheck test package coverageReport
- sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
# Trick to avoid unnecessary cache updates
- find $HOME/.sbt -name "*.lock" | xargs rm

notifications:
  slack:
    rooms:
      - $SLACK_TOKEN
    on_success: change
    on_failure: always

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coveralls
  - >
    if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_REPO_SLUG" = "Scout24/toguru-scala-client" ]; then
      if [[ $TRAVIS_TAG ]]; then
        ./publish-bintray-release.sh;
      fi
    fi
